import type { Metadata } from 'next';
import s from './style.module.scss';
import { Header, VStack } from '@/components/ui';

export const metadata: Metadata = {
	title: '2025 소프트웨어나눔축제',
	description: 'Generated by create next app',
};

export default function CampLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
        <VStack className={s.container} align='start' justify='start'>
            <Header/>
            {children}
        </VStack>
    )
}