import type { Metadata } from 'next';
import { Analytics } from "@vercel/analytics/next"

import '@/styles/global.scss';
import { paperlogy } from '@/utils/font';

export const metadata: Metadata = {
	title: '2025 소프트웨어나눔축제',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${paperlogy.className}`}>{children}</body>
			<Analytics />
		</html>
	);
}
